/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminCustomerOnboardRouteImport } from './routes/_admin.customer-onboard'
import { Route as AdminCustomersRouteImport } from './routes/_admin.customers'
import { Route as AdminOrdersRouteImport } from './routes/_admin.orders'
import { Route as AdminPendingAccountsRouteImport } from './routes/_admin.pending-accounts'
import { Route as AdminProductsRouteImport } from './routes/_admin.products'
import { Route as AdminCustomerIdRouteImport } from './routes/_admin.customer.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/_admin.orders_.$id'
import { Route as AdminOrdersNewRouteImport } from './routes/_admin.orders_.new'
import { Route as AdminProductsIdRouteImport } from './routes/_admin.products_.$id'
import { Route as AdminProductsNewRouteImport } from './routes/_admin.products_.new'
import { Route as AdminProductsIdEditRouteImport } from './routes/_admin.products_.$id_.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerOnboardRoute = AdminCustomerOnboardRouteImport.update({
  id: '/customer-onboard',
  path: '/customer-onboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingAccountsRoute = AdminPendingAccountsRouteImport.update({
  id: '/pending-accounts',
  path: '/pending-accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerIdRoute = AdminCustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/orders_/new',
  path: '/orders/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products_/$id_/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/customer-onboard': typeof AdminCustomerOnboardRoute
  '/customers': typeof AdminCustomersRoute
  '/orders': typeof AdminOrdersRoute
  '/pending-accounts': typeof AdminPendingAccountsRoute
  '/products': typeof AdminProductsRoute
  '/customer/$id': typeof AdminCustomerIdRoute
  '/orders/$id': typeof AdminOrdersIdRoute
  '/orders/new': typeof AdminOrdersNewRoute
  '/products/$id': typeof AdminProductsIdRoute
  '/products/new': typeof AdminProductsNewRoute
  '/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/customer-onboard': typeof AdminCustomerOnboardRoute
  '/customers': typeof AdminCustomersRoute
  '/orders': typeof AdminOrdersRoute
  '/pending-accounts': typeof AdminPendingAccountsRoute
  '/products': typeof AdminProductsRoute
  '/': typeof AdminIndexRoute
  '/customer/$id': typeof AdminCustomerIdRoute
  '/orders/$id': typeof AdminOrdersIdRoute
  '/orders/new': typeof AdminOrdersNewRoute
  '/products/$id': typeof AdminProductsIdRoute
  '/products/new': typeof AdminProductsNewRoute
  '/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/customer-onboard': typeof AdminCustomerOnboardRoute
  '/_admin/customers': typeof AdminCustomersRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/pending-accounts': typeof AdminPendingAccountsRoute
  '/_admin/products': typeof AdminProductsRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/customer/$id': typeof AdminCustomerIdRoute
  '/_admin/orders_/$id': typeof AdminOrdersIdRoute
  '/_admin/orders_/new': typeof AdminOrdersNewRoute
  '/_admin/products_/$id': typeof AdminProductsIdRoute
  '/_admin/products_/new': typeof AdminProductsNewRoute
  '/_admin/products_/$id_/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customer-onboard'
    | '/customers'
    | '/orders'
    | '/pending-accounts'
    | '/products'
    | '/customer/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/products/$id'
    | '/products/new'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/customer-onboard'
    | '/customers'
    | '/orders'
    | '/pending-accounts'
    | '/products'
    | '/'
    | '/customer/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/products/$id'
    | '/products/new'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/customer-onboard'
    | '/_admin/customers'
    | '/_admin/orders'
    | '/_admin/pending-accounts'
    | '/_admin/products'
    | '/_admin/'
    | '/_admin/customer/$id'
    | '/_admin/orders_/$id'
    | '/_admin/orders_/new'
    | '/_admin/products_/$id'
    | '/_admin/products_/new'
    | '/_admin/products_/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customer-onboard': {
      id: '/_admin/customer-onboard'
      path: '/customer-onboard'
      fullPath: '/customer-onboard'
      preLoaderRoute: typeof AdminCustomerOnboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers': {
      id: '/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pending-accounts': {
      id: '/_admin/pending-accounts'
      path: '/pending-accounts'
      fullPath: '/pending-accounts'
      preLoaderRoute: typeof AdminPendingAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customer/$id': {
      id: '/_admin/customer/$id'
      path: '/customer/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof AdminCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders_/$id': {
      id: '/_admin/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders_/new': {
      id: '/_admin/orders_/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products_/$id': {
      id: '/_admin/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products_/new': {
      id: '/_admin/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products_/$id_/edit': {
      id: '/_admin/products_/$id_/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomerOnboardRoute: typeof AdminCustomerOnboardRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPendingAccountsRoute: typeof AdminPendingAccountsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomerIdRoute: typeof AdminCustomerIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomerOnboardRoute: AdminCustomerOnboardRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPendingAccountsRoute: AdminPendingAccountsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomerIdRoute: AdminCustomerIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
