/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminCustomerOnboardRouteImport } from './routes/_admin.customer-onboard'
import { Route as AdminCustomersRouteImport } from './routes/_admin.customers'
import { Route as AdminOrdersRouteImport } from './routes/_admin.orders'
import { Route as AdminPendingAccountsRouteImport } from './routes/_admin.pending-accounts'
import { Route as AdminCustomerIdRouteImport } from './routes/_admin.customer.$id'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerOnboardRoute = AdminCustomerOnboardRouteImport.update({
  id: '/customer-onboard',
  path: '/customer-onboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingAccountsRoute = AdminPendingAccountsRouteImport.update({
  id: '/pending-accounts',
  path: '/pending-accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerIdRoute = AdminCustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/customer-onboard': typeof AdminCustomerOnboardRoute
  '/customers': typeof AdminCustomersRoute
  '/orders': typeof AdminOrdersRoute
  '/pending-accounts': typeof AdminPendingAccountsRoute
  '/customer/$id': typeof AdminCustomerIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/customer-onboard': typeof AdminCustomerOnboardRoute
  '/customers': typeof AdminCustomersRoute
  '/orders': typeof AdminOrdersRoute
  '/pending-accounts': typeof AdminPendingAccountsRoute
  '/': typeof AdminIndexRoute
  '/customer/$id': typeof AdminCustomerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/customer-onboard': typeof AdminCustomerOnboardRoute
  '/_admin/customers': typeof AdminCustomersRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/pending-accounts': typeof AdminPendingAccountsRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/customer/$id': typeof AdminCustomerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/customer-onboard'
    | '/customers'
    | '/orders'
    | '/pending-accounts'
    | '/customer/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/customer-onboard'
    | '/customers'
    | '/orders'
    | '/pending-accounts'
    | '/'
    | '/customer/$id'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/customer-onboard'
    | '/_admin/customers'
    | '/_admin/orders'
    | '/_admin/pending-accounts'
    | '/_admin/'
    | '/_admin/customer/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customer-onboard': {
      id: '/_admin/customer-onboard'
      path: '/customer-onboard'
      fullPath: '/customer-onboard'
      preLoaderRoute: typeof AdminCustomerOnboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers': {
      id: '/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pending-accounts': {
      id: '/_admin/pending-accounts'
      path: '/pending-accounts'
      fullPath: '/pending-accounts'
      preLoaderRoute: typeof AdminPendingAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customer/$id': {
      id: '/_admin/customer/$id'
      path: '/customer/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof AdminCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCustomerOnboardRoute: typeof AdminCustomerOnboardRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPendingAccountsRoute: typeof AdminPendingAccountsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomerIdRoute: typeof AdminCustomerIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCustomerOnboardRoute: AdminCustomerOnboardRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPendingAccountsRoute: AdminPendingAccountsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomerIdRoute: AdminCustomerIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
