/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/_admin.index'
import { Route as AdminBillingRouteImport } from './routes/_admin.billing'
import { Route as AdminCustomerOnboardRouteImport } from './routes/_admin.customer-onboard'
import { Route as AdminCustomersRouteImport } from './routes/_admin.customers'
import { Route as AdminDispatchRouteImport } from './routes/_admin.dispatch'
import { Route as AdminOrdersRouteImport } from './routes/_admin.orders'
import { Route as AdminPendingAccountsRouteImport } from './routes/_admin.pending-accounts'
import { Route as AdminProductsRouteImport } from './routes/_admin.products'
import { Route as AdminReturnsRouteImport } from './routes/_admin.returns'
import { Route as AdminSettingsRouteImport } from './routes/_admin.settings'
import { Route as AdminSupportRouteImport } from './routes/_admin.support'
import { Route as AdminCustomerIdRouteImport } from './routes/_admin.customer.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/_admin.orders_.$id'
import { Route as AdminOrdersNewRouteImport } from './routes/_admin.orders_.new'
import { Route as AdminProductsIdRouteImport } from './routes/_admin.products_.$id'
import { Route as AdminProductsNewRouteImport } from './routes/_admin.products_.new'
import { Route as AdminReportsIndexRouteImport } from './routes/_admin.reports.index'
import { Route as AdminReportsCustomerIdRouteImport } from './routes/_admin.reports.$customerId'
import { Route as AdminProductsIdEditRouteImport } from './routes/_admin.products_.$id_.edit'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerOnboardRoute = AdminCustomerOnboardRouteImport.update({
  id: '/customer-onboard',
  path: '/customer-onboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDispatchRoute = AdminDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPendingAccountsRoute = AdminPendingAccountsRouteImport.update({
  id: '/pending-accounts',
  path: '/pending-accounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomerIdRoute = AdminCustomerIdRouteImport.update({
  id: '/customer/$id',
  path: '/customer/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/orders_/$id',
  path: '/orders/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/orders_/new',
  path: '/orders/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/products_/$id',
  path: '/products/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsCustomerIdRoute = AdminReportsCustomerIdRouteImport.update({
  id: '/reports/$customerId',
  path: '/reports/$customerId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsIdEditRoute = AdminProductsIdEditRouteImport.update({
  id: '/products_/$id_/edit',
  path: '/products/$id/edit',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/billing': typeof AdminBillingRoute
  '/customer-onboard': typeof AdminCustomerOnboardRoute
  '/customers': typeof AdminCustomersRoute
  '/dispatch': typeof AdminDispatchRoute
  '/orders': typeof AdminOrdersRoute
  '/pending-accounts': typeof AdminPendingAccountsRoute
  '/products': typeof AdminProductsRoute
  '/returns': typeof AdminReturnsRoute
  '/settings': typeof AdminSettingsRoute
  '/support': typeof AdminSupportRoute
  '/customer/$id': typeof AdminCustomerIdRoute
  '/orders/$id': typeof AdminOrdersIdRoute
  '/orders/new': typeof AdminOrdersNewRoute
  '/products/$id': typeof AdminProductsIdRoute
  '/products/new': typeof AdminProductsNewRoute
  '/reports/$customerId': typeof AdminReportsCustomerIdRoute
  '/reports/': typeof AdminReportsIndexRoute
  '/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/billing': typeof AdminBillingRoute
  '/customer-onboard': typeof AdminCustomerOnboardRoute
  '/customers': typeof AdminCustomersRoute
  '/dispatch': typeof AdminDispatchRoute
  '/orders': typeof AdminOrdersRoute
  '/pending-accounts': typeof AdminPendingAccountsRoute
  '/products': typeof AdminProductsRoute
  '/returns': typeof AdminReturnsRoute
  '/settings': typeof AdminSettingsRoute
  '/support': typeof AdminSupportRoute
  '/': typeof AdminIndexRoute
  '/customer/$id': typeof AdminCustomerIdRoute
  '/orders/$id': typeof AdminOrdersIdRoute
  '/orders/new': typeof AdminOrdersNewRoute
  '/products/$id': typeof AdminProductsIdRoute
  '/products/new': typeof AdminProductsNewRoute
  '/reports/$customerId': typeof AdminReportsCustomerIdRoute
  '/reports': typeof AdminReportsIndexRoute
  '/products/$id/edit': typeof AdminProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/billing': typeof AdminBillingRoute
  '/_admin/customer-onboard': typeof AdminCustomerOnboardRoute
  '/_admin/customers': typeof AdminCustomersRoute
  '/_admin/dispatch': typeof AdminDispatchRoute
  '/_admin/orders': typeof AdminOrdersRoute
  '/_admin/pending-accounts': typeof AdminPendingAccountsRoute
  '/_admin/products': typeof AdminProductsRoute
  '/_admin/returns': typeof AdminReturnsRoute
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/support': typeof AdminSupportRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/customer/$id': typeof AdminCustomerIdRoute
  '/_admin/orders_/$id': typeof AdminOrdersIdRoute
  '/_admin/orders_/new': typeof AdminOrdersNewRoute
  '/_admin/products_/$id': typeof AdminProductsIdRoute
  '/_admin/products_/new': typeof AdminProductsNewRoute
  '/_admin/reports/$customerId': typeof AdminReportsCustomerIdRoute
  '/_admin/reports/': typeof AdminReportsIndexRoute
  '/_admin/products_/$id_/edit': typeof AdminProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/billing'
    | '/customer-onboard'
    | '/customers'
    | '/dispatch'
    | '/orders'
    | '/pending-accounts'
    | '/products'
    | '/returns'
    | '/settings'
    | '/support'
    | '/customer/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/products/$id'
    | '/products/new'
    | '/reports/$customerId'
    | '/reports/'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/billing'
    | '/customer-onboard'
    | '/customers'
    | '/dispatch'
    | '/orders'
    | '/pending-accounts'
    | '/products'
    | '/returns'
    | '/settings'
    | '/support'
    | '/'
    | '/customer/$id'
    | '/orders/$id'
    | '/orders/new'
    | '/products/$id'
    | '/products/new'
    | '/reports/$customerId'
    | '/reports'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/billing'
    | '/_admin/customer-onboard'
    | '/_admin/customers'
    | '/_admin/dispatch'
    | '/_admin/orders'
    | '/_admin/pending-accounts'
    | '/_admin/products'
    | '/_admin/returns'
    | '/_admin/settings'
    | '/_admin/support'
    | '/_admin/'
    | '/_admin/customer/$id'
    | '/_admin/orders_/$id'
    | '/_admin/orders_/new'
    | '/_admin/products_/$id'
    | '/_admin/products_/new'
    | '/_admin/reports/$customerId'
    | '/_admin/reports/'
    | '/_admin/products_/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/billing': {
      id: '/_admin/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customer-onboard': {
      id: '/_admin/customer-onboard'
      path: '/customer-onboard'
      fullPath: '/customer-onboard'
      preLoaderRoute: typeof AdminCustomerOnboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers': {
      id: '/_admin/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dispatch': {
      id: '/_admin/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AdminDispatchRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders': {
      id: '/_admin/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/pending-accounts': {
      id: '/_admin/pending-accounts'
      path: '/pending-accounts'
      fullPath: '/pending-accounts'
      preLoaderRoute: typeof AdminPendingAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products': {
      id: '/_admin/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/returns': {
      id: '/_admin/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/support': {
      id: '/_admin/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customer/$id': {
      id: '/_admin/customer/$id'
      path: '/customer/$id'
      fullPath: '/customer/$id'
      preLoaderRoute: typeof AdminCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders_/$id': {
      id: '/_admin/orders_/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders_/new': {
      id: '/_admin/orders_/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products_/$id': {
      id: '/_admin/products_/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products_/new': {
      id: '/_admin/products_/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports/': {
      id: '/_admin/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports/$customerId': {
      id: '/_admin/reports/$customerId'
      path: '/reports/$customerId'
      fullPath: '/reports/$customerId'
      preLoaderRoute: typeof AdminReportsCustomerIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/products_/$id_/edit': {
      id: '/_admin/products_/$id_/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AdminProductsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminCustomerOnboardRoute: typeof AdminCustomerOnboardRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDispatchRoute: typeof AdminDispatchRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPendingAccountsRoute: typeof AdminPendingAccountsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCustomerIdRoute: typeof AdminCustomerIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminReportsCustomerIdRoute: typeof AdminReportsCustomerIdRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminProductsIdEditRoute: typeof AdminProductsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminCustomerOnboardRoute: AdminCustomerOnboardRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDispatchRoute: AdminDispatchRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPendingAccountsRoute: AdminPendingAccountsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCustomerIdRoute: AdminCustomerIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminReportsCustomerIdRoute: AdminReportsCustomerIdRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminProductsIdEditRoute: AdminProductsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
